// Durable-DAV-Router Env shape for isolated package typechecks.
// Apps additionally include worker-configuration.d.ts (generated by
// `wrangler types`); bindings are `any` here so `env.DB` is usable without
// @cloudflare/workers-types. The router is stateless: D1 + KV lookaside, no DOs.
declare global {
  interface Env {
    DB: any;
    CACHE?: any;
    DEBUG_MODE?: string;
    ENVIRONMENT?: string;
    DEV_AUTH_EMAIL?: string;
    DEMO_MODE?: string;
    DEMO_USER_EMAIL?: string;
    POLICY_AUD?: string;
    TEAM_DOMAIN?: string;
    SITE_URL?: string;
    MAX_BACKENDS_PER_USER?: string;
    BACKEND_FETCH_TIMEOUT_MS?: string;
    ROUTE_CACHE_TTL_SECONDS?: string;
  }

  type CloudflareEnv = Env;
}

export {};
