-- Migration 0004: `scan_state.consecutive_failures`, so a failed scan is retried once
-- and not for ever.
--
-- ### The defect this records
--
-- `ScanService.step` short-circuits whenever `scan_state.status !== 'scanning'`, and
-- `fail` sets `status = 'failed'`. So the next poll returned the stored failure and
-- did no work — permanently. The frontier was still in D1, fully intact, and nothing
-- would ever read it again: a scan that had visited one folder of eighty stayed at one
-- folder for the life of the deployment.
--
-- The module header claimed the opposite — "a failure leaves the frontier where it was,
-- so the next poll resumes rather than restarting" — and the claim was true of the
-- frontier and false of the code that reads it. Only `startScan` recovered, and
-- `startScan` is called at startup by a client, not while somebody browses.
--
-- Worse, the failure was invisible. `getScanStatus` mapped `scanning` to
-- `scanning: result.status === 'scanning'`, so `'failed'` and `'idle'` serialized
-- identically: `{"scanning": false, "count": 1}` for both a finished scan and a wedged
-- one. A client reads that as "done" and stops polling. The reason was in
-- `scan_state.last_error` the entire time, readable only from `/user/*` behind
-- Cloudflare Access.
--
-- ### Why the counter is in D1
--
-- Because it has to survive the isolate. A module-level counter resets whenever a
-- different isolate serves the next poll, so a scan on a busy deployment would retry
-- its permanent fault indefinitely — which is the outcome this column exists to
-- prevent. `scan_state` is already the scan's durable state, so this is where it
-- belongs.
--
-- Bounded rather than unlimited on purpose. Retrying a *transient* fault is the whole
-- point: a WebDAV origin that 500s once should not end a scan. Retrying a *permanent*
-- one is a loop that spends the operator's subrequest budget to arrive at the same
-- conclusion. So the bound is on consecutive failures, and `markScanning` — an
-- explicit request to scan — resets it, which is the operator's escape hatch and needs
-- no new surface.
ALTER TABLE scan_state ADD COLUMN consecutive_failures INTEGER NOT NULL DEFAULT 0;
