-- The path-derived grouping needs a version of its own.
--
-- ### Why this column exists
--
-- `upsertFileFacts` derives `album`/`artist` from `dir_path` when a row has none, and
-- that derivation is correct for every file the indexer has *touched*. It is
-- structurally unreachable for every file it has not, because all three call sites
-- gate on change:
--
--   - `ScanService.start`  - a root `Depth: 0` probe whose mtime matches settles the
--     whole library in one subrequest.
--   - `scanFolder`         - `isScanned: !changed`, so an unmoved folder is never opened.
--   - `reconcileFolder`    - `if (changed)`, so an unmoved file is never upserted.
--   - `TreeService`        - the read-through `getMusicDirectory` path skips a file
--     present in both listings with an identical mtime.
--
-- So for an already-indexed library the derivation never runs, and the aggregates stay
-- empty. It shipped exactly that way: 113 rows, all indexed before the deploy, all with
-- `album_ci`/`artist_ci` NULL, and `getArtists`/`getAlbumList2`/`getGenres`/`search3`
-- answering `[]` while `getRandomSongs` — which does not group — returned rows that
-- *looked* tagged, because the song mapper falls back to the folder name for display.
--
-- ### Why a version and not just "is the column NULL"
--
-- Because "is it NULL" cannot express a *corrected* convention. Once an earlier
-- derivation has written a value, those columns are no longer NULL, so a later, better
-- `pathConvention` could never reach the rows the earlier one wrote — which is the
-- `reader_version` defect verbatim, one layer down: a fixed reader could not re-read an
-- existing library, and a fixed derivation would not re-derive one.
--
-- So the derivation is stamped, and the backfill selects on the stamp rather than on the
-- value. Bumping `DERIVED_VERSION` re-derives everything, and the `COALESCE` in the
-- write keeps a real tag winning over either.
ALTER TABLE songs ADD COLUMN derived_version INTEGER NOT NULL DEFAULT 0;

-- Serves the backfill's own selection, `derived_version < ?`, scoped to one library.
--
-- The existing `(library_id, album_ci)` index cannot serve it: a drained library has
-- every row at the current version, so the predicate is a range scan on a column nothing
-- else filters by. A `(library_id, derived_version)` index makes it a seek that returns
-- nothing immediately once the library is caught up — which is what keeps a poll on a
-- fully-derived library costing one indexed read and zero rows.
CREATE INDEX IF NOT EXISTS idx_songs_derived ON songs(library_id, derived_version);
