-- Provenance for the path-derived grouping, in a column rather than in the value.
--
-- ### What this replaces
--
-- Until now the only record that a row's `artist`/`album`/`album_artist` came from
-- `dir_path` rather than from a file's tags was the **suffix on the value itself**:
-- `pathConvention`'s `DERIVED_MARKER`, ` (derived)`. `applyDerivation` read it back out
-- of the stored string —
--
--   artist = CASE WHEN artist IS NULL OR artist LIKE '% (derived)' THEN ? ELSE artist END
--
-- and that branch is the entire reason a `derived_version` bump can tell a guess it wrote
-- from a tag a file supplied. It is also why an operator could not choose the marker.
--
-- ### Why the marker had to stop being the record
--
-- Two failures, both silent, both measured over real SQLite against this statement.
--
-- **An empty marker is a match-all.** `'%' || ''` is `'%'`, which matches every non-NULL
-- value, so the `ELSE` branch becomes unreachable and the backfill overwrites *every* real
-- `ALBUMARTIST` in the library — the precise failure the paired test in
-- `test/schema.int.test.ts` exists to prevent. An empty marker is the requested default,
-- because an empty marker is what makes a derived `X` and a tagged `X` the same album
-- rather than two.
--
-- **Any other marker is a `LIKE` pattern, not a literal.** An operator writing
-- `_ (guess)` gets `'%_ (guess)'`, where `_` matches any single character — so the guard
-- stops recognising its *own* guesses as well. A version bump then re-selects those rows
-- and declines to change them: the `reader_version` defect verbatim, one layer down, with
-- no error anywhere. `'%'` as a marker matches everything, which is the first failure
-- again.
--
-- So the guard cannot be a string operation. It has to be a column comparison.
--
-- ### Why this is not `derived_version` doing one more job
--
-- `derived_version` answers "which convention version last *examined* this row", and it is
-- stamped unconditionally — including on a row holding a real tag, which is equally not
-- owed a derivation. Repurposing it to mean "which version last *wrote* the grouping"
-- breaks the selection: a tagged row would sit at `0`, satisfy `derived_version < ?` on
-- every poll for ever, and the backfill would never converge. Stamping it to stop that
-- makes the next bump overwrite the tag instead. Two inputs need two columns — the rule
-- `reader_version` and `derived_version` already follow.
--
-- ### The definition, which is one sentence
--
-- `'derived'` means **all three** grouping columns came from the path. Anything else is
-- NULL.
--
-- "All three" rather than "any one" is the conservative direction and it is deliberate. A
-- row that carries a tagged `artist` and a path-derived `album` is not wholly a guess, so
-- a later correction of the convention may not rewrite it — the cost is that such a row's
-- derived component is permanent, which is the right way round, because the alternative
-- direction lets a correction overwrite a real tag. Three columns
-- (`artist_source`/`album_source`/`album_artist_source`) would preserve today's per-column
-- guard exactly, at the cost of tripling the surface that has to move in step with every
-- `_ci` twin.
--
-- ### The backfill below is the only place the old marker is written down
--
-- `' (derived)'` is a literal in this file and nowhere in the codebase. This is the one
-- place it belongs: it is a fact about rows written before this column existed, and the
-- code that will read them no longer knows the string. A migration is immutable once
-- applied — see `applied.lock.json`.
ALTER TABLE songs ADD COLUMN grouping_source TEXT;

-- Rows the old convention grouped. The three columns move together — `upsertFileFacts`
-- writes all three or none — so any one of them identifies the row, and `OR` is the safe
-- reading of that rather than an attempt to be clever about a partial state.
--
-- Only `artist` and `album` are tested. `album_artist` is written from the derived artist,
-- so a row that is wholly derived has both, and a row with a real `artist` is not wholly
-- derived whatever its `album_artist` holds.
UPDATE songs SET grouping_source = 'derived'
 WHERE artist LIKE '% (derived)'
    OR album LIKE '% (derived)'
    OR album_artist LIKE '% (derived)';

-- No index. `grouping_source` is read only inside the `WHERE id = ?` of `applyDerivation`
-- and written by two upserts; it is never a selection predicate, so an index on it would
-- be paid for on every write and used by nothing. `idx_songs_derived` already serves the
-- selection this column participates in.