/**
 * The Subsonic ID scheme.
 *
 * Subsonic IDs are opaque strings, and clients hold onto them for a long time:
 * a saved playlist, a play queue, a starred album, and a bookmark all keep IDs
 * across restarts and across devices. That rules out anything minted per request.
 *
 * So IDs are **reversible** — `kind:base64url(libraryId + "\n" + path)` — and
 * three properties follow (for every kind **except songs**, which are now short
 * and opaque — see `songId.ts` — and resolve through the row):
 *
 * 1. Resolving an ID to a path costs a base64 decode, so `stream` never needs a
 *    database lookup to know *what* to fetch. The hot path stays off D1 and KV.
 *    (Songs are the exception: their ids outgrew client filenames, so `stream`
 *    reads the row first.)
 * 2. The `kind` prefix makes the ID self-describing, so `getCoverArt` and
 *    `stream` dispatch on the prefix instead of a lookup table.
 * 3. A rename or a move is not a data migration — the same path yields the same
 *    ID forever. (Songs are stable the same way: the id is derived from
 *    `(library_id, path)`, so a rescan after an index drop recreates it, and
 *    the id backfill renames long ids to the derived short form.)
 *
 * Property 3 has a consequence that is easy to get wrong and is load-bearing:
 * an **album** ID must resolve back to its songs, so the payload has to be
 * whatever the resolution actually reads. While an album *was* a directory that
 * meant `dir_path` and never an album name — rename the folder and a name-derived
 * id orphans every star, silently. An album's identity is configurable now
 * (`albumKey.ts`), so the payload is the grouping key and the kind prefix says
 * so. The rule underneath is unchanged and is the one to keep: **the payload is
 * the resolution's own input**, so the two cannot be changed apart.
 *
 * ### Ids are forgeable
 *
 * A client can hand-craft `s:<b64url(libA|../../etc/passwd)>` and nothing about
 * the format stops it. This file is therefore a *parser for untrusted input*,
 * not a convenience: `decodeId` enforces the type prefix, the library-id
 * character set that makes the separator unambiguous, and path containment.
 * Whether the *caller* is entitled to that library is checked by the service
 * layer, not here.
 */
import { ErrorCode, SubsonicError } from './errors';

/**
Discriminator carried in the ID prefix.
*/
const IdKind = {
  /**
  A music directory (any folder, from `getIndexes`/`getMusicDirectory`).
  */
  Directory: 'dir',
  /**
  A music folder root (a registered library, from `getMusicFolders`).

  Never minted. A `musicFolderId` is a **position** in the folder list, not an id —
  the schema types it as an `integer` — so there is nothing here to encode. Kept
  because a reserved kind that is documented costs nothing and an unreserved one
  would make a forged prefix look legitimate.
  */
  MusicFolder: 'mf',
  /**
  A directory-based artist (`getIndexes`).
  */
  DirectoryArtist: 'dira',
  /**
  A tag-derived artist (`getArtists`/`getArtist`).
  */
  Artist: 'ar',
  /**
  An album.

  A **directory** path. Still accepted, and still resolvable, because clients hold album ids
  for a long time — in a star, in a rating, in a saved playlist — and an id this server can no
  longer decode is an album that silently disappeared from someone's library. Nothing mints it
  any more; {@link IdKind.AlbumKey} is what the publishers emit. See `albumKey.ts`.
  */
  Album: 'al',
  /**
  An album named by its **grouping key** rather than by a directory.

  The kind exists because the key is not a path, and because two keys must be told apart on the
  wire. An album's identity is `ALBUM_GROUP_BY`'s answer to "which tracks are this album", which
  is a tag for most libraries and only a directory for some — so the id has to carry the key,
  and the prefix is what says the payload is a key rather than a folder, with no heuristic
  guessing between two shapes that are both ordinary relative paths.
  */
  AlbumKey: 'alk',
  /**
  A song.
  */
  Song: 's',
  /**
  Reserved for `getVideos`. Never issued while videos are unimplemented.
  */
  Video: 'vid',
} as const;

type IdKindValue = (typeof IdKind)[keyof typeof IdKind];

const ALL_ID_KINDS: readonly string[] = Object.values(IdKind);

/**
 * Separates the library id from the path inside the encoded payload.
 *
 * A newline cannot appear in either half: a library id is minted from the
 * base64url alphabet (asserted on decode), and a WebDAV path is percent-encoded
 * before it is stored. So the split is unambiguous rather than "first separator
 * wins", which is what a space or colon would have been.
 */
const SEPARATOR = '\n';

/**
 * Library ids are generated by this server, so their alphabet is known and can
 * be *enforced* on the way back in. That enforcement is what makes `SEPARATOR`
 * safe — without it, a crafted id could smuggle a separator into the library
 * half and shift the boundary between the two fields.
 */
const LIBRARY_ID_PATTERN = /^[\w-]{1,64}$/i;

/**
 * The library id an **album or artist** id carries when that release spans every library the
 * caller can see, rather than one of them.
 *
 * ### Why a sentinel rather than dropping the library half
 *
 * Every id is `<kind>:base64url(<libraryId>\n<path>)`, and `decodeId` **requires** a library
 * half: a missing one is `separator <= 0`, which is a `code=70`. So "an album id that names no
 * library" is not a payload this repository can currently express, and adding a branch to a
 * validator that every id on every surface passes through is a much larger change than the
 * feature needs.
 *
 * The sentinel is therefore a value that is a legal library id and **not a library**:
 * `LIBRARY_ID_PATTERN` accepts it, and `LibraryDAO` mints v4 UUIDs, so it is never assigned.
 * All-zeros is the same placeholder `wrangler.template.jsonc` already carries for an
 * unconfigured `database_id`, which is the point — it reads as "no particular library" rather
 * than as a fourth library somebody forgot to delete. Asserted unforgeable-and-unassignable in
 * `test/music-folder-index.test.ts`.
 *
 * ### And why albums and artists need it at all
 *
 * Two libraries can hold one album — the measured case is a release whose track 01 is in one
 * library and track 03 in another. Under a per-library id they are **two** albums, so a union
 * lists the release twice at a `songCount` of 1 each, and a client that opened one cannot see
 * the other's track. The id is what says "one album", so it cannot name one library.
 *
 * A **song** id still carries a real library, because `path` is only meaningful inside one: the
 * same relative path in two libraries is two files, and collapsing them would point a star at
 * whichever was written last. So the sentinel is scoped to the two ids that name a *group*.
 */
const SPANNING_LIBRARY_ID = '00000000-0000-0000-0000-000000000000';

function toBase64Url(bytes: Uint8Array): string {
  let binary = '';
  // Chunked to stay clear of the argument-count limit on large payloads.
  const CHUNK = 0x80_00;
  for (let index = 0; index < bytes.length; index += CHUNK) {
    binary += String.fromCharCode(...bytes.subarray(index, index + CHUNK));
  }
  return btoa(binary).replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/, '');
}

function fromBase64Url(value: string): Uint8Array {
  const padded = value.replaceAll('-', '+').replaceAll('_', '/');
  const binary = atob(padded + '='.repeat((4 - (padded.length % 4)) % 4));
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes;
}

/**
 * Validate and canonicalize a library-relative path.
 *
 * Returns `null` — rather than throwing — so callers can decide whether a
 * rejection is a `code=70` (this id does not exist) or a `code=0` (this id is
 * malformed). It is deliberately strict:
 *
 * - no leading `/` (the path is relative to the library root, and an absolute
 *   path is an attempt to escape it),
 * - no `.` or `..` segments, before *and* after decoding — percent-encoded
 *   traversal (`%2e%2e%2f`) is the same attack with extra steps,
 * - no empty segments, so `a//b` cannot be used to produce two spellings of one
 *   path (which would defeat the `UNIQUE (library_id, path)` index and let two
 *   rows describe the same file),
 * - no backslash and no NUL, both of which some WebDAV servers and filesystems
 *   normalize differently from the URL layer.
 */
function normalizeRelativePath(path: string): string | null {
  if (path.length === 0 || path.length > 1024 || path.includes('\0') || path.includes('\\')) return null;
  // Control characters are refused for a structural reason, not a cosmetic one: the
  // payload is split on a newline, so a path containing one would make the
  // library/path boundary ambiguous to anything that splits it differently. A
  // filename with a newline in it is pathological, and refusing it is free.
  // eslint-disable-next-line no-control-regex -- the control characters ARE the check.
  if (/[\u0000-\u001F\u007F]/.test(path)) return null;
  if (path.startsWith('/') || path.endsWith('/')) return null;

  const segments = path.split('/');
  for (const segment of segments) {
    if (segment.length === 0 || segment === '.' || segment === '..') return null;
  }
  return segments.join('/');
}

/**
Build a Subsonic ID.
*/
function encodeId(kind: IdKindValue, libraryId: string, path: string): string {
  const payload = `${libraryId}${SEPARATOR}${path}`;
  return `${kind}:${toBase64Url(new TextEncoder().encode(payload))}`;
}

interface DecodedId {
  kind: IdKindValue;
  libraryId: string;
  path: string;
}

/**
 * Decode a Subsonic ID supplied by a client.
 *
 * @param expected When given, the decoded kind must match. `getCoverArt` and
 *   `stream` both receive an `id` and would otherwise happily resolve an album
 *   id as a song path, so the endpoint states what it accepts.
 * @throws SubsonicError `code=70` — a malformed or mismatched id names a
 *   resource that does not exist, which is also what an id for a resource the
 *   caller may not see should look like. Using `code=50` here would confirm the
 *   id is real, turning the endpoint into an oracle.
 */
function decodeId(raw: string, expected?: IdKindValue): DecodedId {
  // A function declaration, not an arrow assigned to a const: TypeScript only
  // treats a call as never-returning for control-flow analysis when the
  // declaration is a function with an explicit `never` return type, and without
  // that every use below is "used before being assigned".
  function fail(): never {
    throw new SubsonicError(ErrorCode.NotFound);
  }

  if (typeof raw !== 'string' || raw.length === 0 || raw.length > 2048) fail();

  const colon = raw.indexOf(':');
  if (colon <= 0 || colon === raw.length - 1) fail();

  const kind = raw.slice(0, colon);
  if (!ALL_ID_KINDS.includes(kind)) fail();
  if (expected !== undefined && kind !== expected) fail();

  // `atob` throws `InvalidCharacterError` on a malformed payload. Letting that
  // escape would make a forged id produce a 500 with a platform error message
  // instead of the `code=70` a client can parse.
  let payload: Uint8Array;
  try {
    payload = fromBase64Url(raw.slice(colon + 1));
  } catch {
    fail();
  }
  const separator = payload.indexOf(0x0a);
  if (separator <= 0) fail();

  const decoder = new TextDecoder('utf-8', { fatal: true });
  let libraryId: string;
  let path: string;
  try {
    libraryId = decoder.decode(payload.subarray(0, separator));
    path = decoder.decode(payload.subarray(separator + 1));
  } catch {
    fail();
  }

  if (!LIBRARY_ID_PATTERN.test(libraryId)) fail();

  const normalized = normalizeRelativePath(path);
  if (normalized === null) fail();

  // `encodeId` stores the path *decoded*, so a percent escape here means the id was
  // not produced by this server. Refusing it is what keeps a consumer from having to
  // decide whether `%2e%2e%2f` is a literal filename or an encoded traversal.
  if (/%[\da-f]{2}/i.test(normalized)) fail();

  return { kind: kind as IdKindValue, libraryId, path: normalized };
}

export {
  IdKind,
  encodeId,
  decodeId,
  normalizeRelativePath,
  LIBRARY_ID_PATTERN,
  SPANNING_LIBRARY_ID,
  SEPARATOR,
  toBase64Url,
  fromBase64Url,
};
export type { IdKindValue, DecodedId };
