// Bindings for this worker, generated by `pnpm run typegen` into the repository root.
// `Cloudflare.Env` is used explicitly rather than through a global `Env` alias, so a
// typo in a binding name is a type error instead of an implicit `any`.
export {};
